FROM resin/raspberrypi3-debian:stretch

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends python-pip libboost-python1.62.0 && \
    rm -rf /var/lib/apt/lists/* 

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

CMD [ "python", "-u", "./main.py" ]