FROM python:2

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install -r requirements.txt

RUN apt-get update
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y openmpi-bin openmpi-common
RUN apt-get install -y libboost1.58-all-dev

COPY . .

CMD [ "python", "./main.py", "-p", "mqtt", "-c", "HostName=azure-iot-toolkit-for-mobile.azure-devices.net;DeviceId=a0226;SharedAccessKey=UgR3yxTXxg0xdJDbz9P9ejUu8urtWVWa0C0/wcPUYEU=;ModuleId=PythonModule;GatewayHostName=junhan2017.fareast.corp.microsoft.com" ]