FROM resin/raspberrypi3-python:2.7

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libboost-python1.55.0 && \
    rm -rf /var/lib/apt/lists/* 

COPY requirements-debug.txt ./
RUN pip install -r requirements-debug.txt

COPY . .

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT [ "python", "-u", "./filter.debug.py" ]