FROM yorek/anaconda3-windowservercore:latest

WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

ADD https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x64.exe C:/vc_redist.x64.exe
RUN C:\vc_redist.x64.exe /quiet /install

CMD ["python", "-u", "filter.py"]