FROM python:3.6-slim-jessie

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install -r requirements.txt

RUN apt-get update
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y openmpi-bin openmpi-common
RUN apt-get install -y libboost1.58-all-dev

COPY . .

CMD [ "python", "./main.py" ]